# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Desktop/Stuff/vivado-projects/projects/graphics/constrs/main.xdc

# IP: D:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: D:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/v_tc_0/v_tc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] -quiet

# IP: D:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/rgb2dvi_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/v_tc_0/v_tc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Desktop/Stuff/vivado-projects/projects/graphics/src/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
